version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo installing nodejs...
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt-get install -y nodejs  #aws code build use ubuntu environement
  pre_build:
    commands:
      - echo installing dependencies...
      - npm install -g @angular/cli
      - npm install
  build:
    commands:
      # - echo testing...
      # - echo building...
      - ng build --prod || exit 0
  post_build:
    commands:
      - mv appspec.yml ./dist/myapp1
      - mv scripts ./dist/myapp1
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/myapp1